name: programmingwithkumaresan

trigger: none

pr: none

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: Downloading & Installing Essentials
  inputs:
    targetType: inline
    script: |
      Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
      cmd /c Downloads.bat

- task: CmdLine@2
  displayName: Log In To AnyDesk
  inputs:
    script: |
      cmd /c show.bat

- task: CmdLine@2
  displayName: Time Counter
  inputs:
    script: |
      python time.py
