trigger: none
pr: none

name: Windows-LiteManager

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  displayName: 'Start Building'
  timeoutInMinutes: 9999

  steps:
  - checkout: self

  - task: PowerShell@2
    displayName: 'Downloading & Installing Essentials'
    inputs:
      targetType: 'inline'
      script: |
        Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
        cmd /c Downloads.bat

  - task: CmdLine@2
    displayName: 'Connect to LiteManager'
    inputs:
      script: |
        call show.bat

  - task: CmdLine@2
    displayName: 'Time Counter'
    inputs:
      script: |
        call loop.bat
